# Generated by Django 5.1 on 2025-01-22 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_color_cartitem_color_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(help_text='Enter a valid HEX code for the color (e.g., #FFFFFF)', max_length=7)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='main.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
