# Generated by Django 5.1 on 2025-01-22 17:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_cartitem_color_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='hex_code',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='color_code',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
