# Generated by Django 5.1 on 2025-01-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_productcolor_hex_code_productcolor_color_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
