# Generated by Django 5.1 on 2025-01-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_newslettersubscriber_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
