# Generated by Django 5.1 on 2025-01-31 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_homepagebanner_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleganceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='elegance_section/')),
                ('title', models.CharField(default='Timeless Elegance, Redefined', max_length=255)),
                ('subtitle', models.TextField(default='Step into a world where luxury is not just worn—it’s lived.')),
            ],
        ),
        migrations.CreateModel(
            name='EleganceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='images/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.elegancesection')),
            ],
        ),
    ]
