# Generated by Django 5.1 on 2025-02-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_elegancesection_elegancefeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='flash_sale/')),
                ('sale_end_time', models.DateTimeField()),
            ],
        ),
    ]
