# Generated by Django 5.1 on 2025-02-09 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_flashsaleproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsaleproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
