# Generated by Django 5.1 on 2025-02-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_flashsaleproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashsaleproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='flashsaleproduct',
            name='original_price',
        ),
    ]
