# Generated by Django 5.1 on 2025-02-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_flashsaleproduct_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
