# Generated by Django 5.1 on 2025-05-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to Our Collection', max_length=200)),
                ('background_image', models.ImageField(upload_to='hero_section/')),
            ],
        ),
    ]
