# Generated by Django 5.1 on 2025-05-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
